### ISSUE TITLE
Why does `texcollab push` not also make a call to `texcollab extras push`?

### ISSUE THREAD

**Issue by avmarchenko** [barrymoo/texcollab#2]
It would be convenient if 

```
texcollab push
```

performed the rsyncing as well. Is there a reason why this is not done?

**Comment by chiroptical** [comment]
First, thanks for putting this on github!

I believe I avoided this in case people were on slow connections. At some point the boss man asked to do as little file transfers as possible. What if I made one extra function called "push-all" which did both?

**Comment by avmarchenko** [comment]
This sounds like a really good solution and provides a simple user convenience.

**Comment by chiroptical** [comment]
Enhancement complete! 91b8d2567c0ec8c533c017ee76f272e49cbbbd90
